import {
  applyWorldCommand,
  createConceptDemoWorld,
  createDemoWorld,
  createCloneDemoWorld,
  createInitedEmptyWorld,
} from '../engine/world';
import type { WorldState } from '../engine/types';
import {
  checkLevel0,
  checkLevel1,
  checkLevel2,
  checkLevel3,
  checkLevel4,
  checkLevel5,
  checkLevel6,
  checkLevel7,
  checkLevel8,
  checkLevel9,
  checkLevel10,
  checkLevelResetSimple,
  checkLevel11,
  checkLevel12,
  checkLevel13,
  checkLevel14,
  checkLevel15,
  checkLevel16,
  checkLevelInitClone,
  checkLevelWorkspace,
  checkLevelAdd,
  checkLevelDiff,
  checkLevelRestore,
  checkLevelStash,
  checkLevelCherryPick,
} from './checks';
import type { LevelDef } from './types';

function mustRun(world: WorldState, cmds: string[]): WorldState {
  let w = world;
  for (const c of cmds) {
    const r = applyWorldCommand(w, c);
    if (!r.ok) throw new Error(`level start failed: ${c} → ${r.stdout.join(' | ')}`);
    w = r.world;
  }
  return w;
}

function startL5(): WorldState {
  return mustRun(createDemoWorld(), [
    'git switch -c feature',
    'git commit -m "feat: feature 独有改动"',
    'git switch main',
  ]);
}

function startL6(): WorldState {
  return mustRun(createDemoWorld(), [
    'git switch -c feature',
    'git commit -m "feat: feature 改动"',
    'git switch main',
    'git commit -m "fix: main 改动"',
  ]);
}

function startL7(): WorldState {
  return mustRun(createDemoWorld(), ['git commit -m "oops: 提交错了"']);
}

function startSoftHard(): WorldState {
  return mustRun(createDemoWorld(), [
    'git commit -m "oops: 多写了一笔"',
    'git commit -m "oops: 又多写了一笔"',
  ]);
}

function startDirty(): WorldState {
  const w = createDemoWorld();
  w.users.alice.dirty = true;
  return w;
}

function startCherryPick(): WorldState {
  return mustRun(createDemoWorld(), [
    'git switch -c feature',
    'git commit -m "feat: 功能开发 1"',
    'git commit -m "fix: 紧急修复登录"',
    'git commit -m "feat: 功能开发 2"',
    'git switch main',
  ]);
}

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    stageId: 's1',
    title: '仓库从哪来：init 与 clone',
    story: '学习 git init 与 git clone：新建空仓库，或从远程复制完整仓库。',
    intro: {
      summary: '本地仓库可以 git init 新建，也可以 git clone 从远程复制一份。',
      detail: 'init 得到空历史；clone 得到完整历史与远程 origin。本沙箱相当于已 init/clone 好的环境。',
    },
    objectiveLabels: ['执行 git init，图上出现仓库起点', '执行 git clone，图上出现远程历史'],
    startWorld: () => createCloneDemoWorld(),
    concepts: [
      {
        id: 'git-init',
        term: '1 · git init',
        teaser: '初始提交图空白，但右侧远程分支列一直保留。',
        body: 'init 之前本地还没有仓库，图主体为空；远程分支始终存在。执行 git init 后才会在图上出现仓库起点等内容。',
        tips: ['空白图 + 远程列保留', 'init 后出现灰色锚点', 'clone 再接到远程历史'],
        graphFocus: 'latest',
        practice: { label: '执行 git init，出现仓库起点', command: 'git init' },
      },
      {
        id: 'git-clone',
        term: '2 · git clone',
        teaser: '从远程复制完整历史，图上会出现整条提交链。',
        body: 'clone 会把远程仓库的提交与分支复制到本地。沙箱执行后，图上将出现远程演示历史（多个圆点与 main）。',
        tips: ['对比 init：clone 一步拿到历史', 'origin 会记在远程引用上', '之后可 push / pull 协作'],
        graphFocus: 'commit',
        practice: { label: '从远程 clone 完整仓库', command: 'git clone' },
      },
    ],
    hints: [
      '第一张卡：git init，看图出现灰色锚点。',
      '第二张卡：git clone，看图出现远程提交链。',
      '注意 init 与 clone 的图上差别。',
    ],
    suggestedCommands: ['git init', 'git clone', 'git status', 'git log --oneline', 'git remote -v'],
    winExplanation: {
      title: '通关：仓库从哪来',
      summary: 'init 新建空仓（只有起点锚点）；clone 从远程复制完整提交历史。',
      detail: '下一关认识 HEAD、提交与分支。',
      related: ['git status', 'git log --oneline'],
    },
    check: ({ after, log }) => checkLevelInitClone(after, log),
  },
  {
    id: 2,
    stageId: 's1',
    title: '认识 HEAD、提交与分支',
    story: '认识 Git 三件套：HEAD、提交、分支，以及它们之间的指向关系。',
    intro: {
      summary: 'Git 用提交保存历史快照，用分支并行推进工作，用 HEAD 标明你当前在哪条线上。',
      detail: '本章搞清：HEAD 指向当前分支；分支指向最新提交；只有 HEAD 所指分支会因 commit 前进。',
    },
    objectiveLabels: ['把 HEAD 指向 feature', '提交说明为「这是我的提交」的 commit', '创建分支 hotfix'],
    startWorld: () => createConceptDemoWorld(),
    concepts: [
      {
        id: 'head',
        term: '1 · HEAD',
        teaser: '看图：橙色 HEAD 现在指向 main。把 HEAD 改为指向 feature。',
        body: 'HEAD 通常指向当前分支名。链路是：HEAD 到当前分支再到该分支最新提交。请把 HEAD 改为指向 feature。',
        tips: ['橙色 HEAD 箭头指向谁，谁就是当前分支', 'commit 只会推进 HEAD 所指向的分支', '切换分支只改 HEAD 的指向'],
        graphFocus: 'head',
        practice: { label: '把 HEAD 从 main 改为指向 feature', command: 'git switch feature' },
      },
      {
        id: 'commit',
        term: '2 · 提交 commit',
        teaser: 'HEAD 指到 feature 后，再记一条说明为「这是我的提交」的提交。',
        body: '提交是历史上的存档点。HEAD 指向 feature 后创建提交，feature 的最新提交会更新。',
        tips: ['一个圆点等于一次 commit', '提交需要写说明信息', '只有 HEAD 指向的分支会前进'],
        graphFocus: 'commit',
        practice: { label: '提交说明为「这是我的提交」', command: 'git commit -m "这是我的提交"' },
      },
      {
        id: 'branch',
        term: '3 · 分支 branch',
        teaser: '图右侧已有 main 和 feature。请再新建名为 hotfix 的分支。',
        body: '分支是贴在某个提交上的名字。请新建 hotfix：刚创建时和当前分支最新提交是同一个圆点。',
        tips: ['hotfix 也是标签名', '新建分支不会立刻改 HEAD', '在分支上 commit，只有这个名字会前进'],
        graphFocus: 'branch',
        practice: { label: '创建新分支 hotfix', command: 'git branch hotfix' },
      },
    ],
    hints: ['建议顺序：HEAD 切到 feature，再建 hotfix，最后提交。', '不要删演示分支 feature。'],
    suggestedCommands: ['git switch feature', 'git branch hotfix', 'git commit -m "这是我的提交"'],
    winExplanation: {
      title: '导读完成',
      summary: 'HEAD 指向当前分支，分支指向最新提交，commit 只推进当前分支。',
      detail: '本关练了切换、新建分支与一次提交。',
      related: ['git switch main', 'git log --oneline', 'git branch'],
    },
    check: ({ after, log }) => checkLevel0(after, log),
  },
  {
    id: 3,
    stageId: 's1',
    title: '第一次提交',
    story: '学习 git commit：在空仓库中创建第一次提交。',
    objectiveLabels: ['在 main 上产生至少 1 个提交'],
    startWorld: () => createInitedEmptyWorld(),
    concepts: [
      {
        id: 'first-commit',
        term: '1 · 第一次 commit',
        teaser: '空仓库还没有任何圆点。给 main 记下第一条存档。',
        body: '空仓库执行提交后，图上 init 上方会出现第一个圆点。',
        tips: ['提交会记在 main 上', '说明写在引号里', '新圆点会闪烁'],
        graphFocus: 'commit',
        practice: { label: '在 main 上创建第一次提交', command: 'git commit -m "init: 第一次提交"' },
      },
    ],
    hints: ['提交需要写一句说明信息。'],
    suggestedCommands: ['git commit -m "init: 第一次提交"', 'git log --oneline'],
    winExplanation: {
      title: '通关：你创建了第一个提交',
      summary: 'main 从尚无提交变成指向新 commit。',
      detail: '本沙箱用 commit 直接代表一次记录。',
      related: ['git log --oneline', 'git status'],
    },
    check: ({ before, after }) => checkLevel1(before, after),
  },
  {
    id: 4,
    stageId: 's1',
    title: '看懂仓库状态',
    story: '学习两条只读命令：git status 查看状态，git log 查看历史。',
    objectiveLabels: ['执行过 git status', '执行过 git log --oneline', '仓库仍有 main 提交'],
    startWorld: () => createDemoWorld(),
    concepts: [
      {
        id: 'status',
        term: '1 · status 查状态',
        teaser: '先看当前分支与工作区。',
        body: 'status 只读，不会改提交图。',
        tips: ['动手前先 status', '关注当前分支'],
        graphFocus: 'head',
        practice: { label: '查看仓库状态', command: 'git status' },
      },
      {
        id: 'log',
        term: '2 · log 看历史',
        teaser: '再看这条分支怎么长出来。',
        body: 'log 按祖先链列出提交。',
        tips: ['新提交在上', '对照提交图'],
        graphFocus: 'latest',
        practice: { label: '查看提交历史', command: 'git log --oneline' },
      },
      {
        id: 'keep-main',
        term: '3 · 不要改图',
        teaser: '本关只观察。',
        body: '不要切换、删除分支，也不要 reset。',
        tips: ['只读命令不改指针'],
        graphFocus: 'latest',
        practice: { label: '再确认一次状态', command: 'git status' },
      },
    ],
    hints: ['status 再 log --oneline。'],
    suggestedCommands: ['git status', 'git log --oneline'],
    winExplanation: {
      title: '通关：会查状态和历史了',
      summary: 'status 看当前状态；log 看历史。',
      detail: '危险操作前先 status + log。',
      related: ['git branch feature'],
    },
    check: ({ before, after, log }) => checkLevel2(before, after, log),
  },
  {
    id: 5,
    stageId: 's2',
    title: '创建分支（先不切换 HEAD）',
    story: '学习 git branch：创建分支指针，且不切换 HEAD。',
    objectiveLabels: ['创建分支 feature', 'HEAD 仍在 main 上', 'feature 与 main 指向同一提交'],
    startWorld: () => createDemoWorld(),
    concepts: [
      {
        id: 'create-branch',
        term: '1 · 建分支不切换',
        teaser: '给最新提交再贴一个名字 feature。',
        body: '只创建分支指针，不修改 HEAD。',
        tips: ['同一圆点挂两个名字', 'HEAD 仍指向 main'],
        graphFocus: 'branch',
        practice: { label: '创建 feature（不要切换）', command: 'git branch feature' },
      },
      {
        id: 'stay-main',
        term: '2 · HEAD 仍在 main',
        teaser: '确认没有切换过去。',
        body: '用 status 确认当前分支仍是 main。',
        tips: ['status 只读'],
        graphFocus: 'head',
        practice: { label: '确认 HEAD 仍指向 main', command: 'git status' },
      },
      {
        id: 'same-commit',
        term: '3 · 两分支尚未分叉',
        teaser: 'feature 与 main 指向同一提交。',
        body: '还没有各自 commit。',
        tips: ['同一圆点可挂多个分支名'],
        graphFocus: 'latest',
        practice: { label: '用 log 对照', command: 'git log --oneline' },
      },
    ],
    hints: ['branch feature，再 status，再 log。'],
    suggestedCommands: ['git branch feature', 'git status', 'git log --oneline'],
    winExplanation: {
      title: '通关：分支只是指针',
      summary: 'feature 和 main 指到同一个提交。',
      detail: '下一关让 feature 变长。',
      related: ['git switch feature', 'git commit -m "feat: ..."'],
    },
    check: ({ before, after, log }) => checkLevel3(before, after, log),
  },
  {
    id: 6,
    stageId: 's2',
    title: '切换分支并提交',
    story: '学习切换分支后提交，观察历史如何分叉。',
    objectiveLabels: ['HEAD 在 feature 上', 'feature 上至少有 1 个 main 没有的提交', 'main 最新提交未变'],
    startWorld: () => createDemoWorld(),
    concepts: [
      {
        id: 'switch-feature',
        term: '1 · HEAD 指向 feature',
        teaser: '让 HEAD 指向 feature。',
        body: '切换分支只是改 HEAD 的指向。',
        tips: ['可一步创建并切换'],
        graphFocus: 'head',
        practice: { label: '创建 feature 并切换', command: 'git switch -c feature' },
      },
      {
        id: 'commit-on-feature',
        term: '2 · 在 feature 上提交',
        teaser: '让 feature 比 main 多一个圆点。',
        body: '只有当前分支会前进。',
        tips: ['说明随意写'],
        graphFocus: 'commit',
        practice: { label: '在 feature 上提交', command: 'git commit -m "feat: 在 feature 上的改动"' },
      },
      {
        id: 'main-unmoved',
        term: '3 · main 不应移动',
        teaser: '对照图：main 的最新提交不能变。',
        body: '这就是分叉。先切回 main，再用 log 对照：main 不应多出 feature 上那一笔。',
        tips: [
          '先执行 git switch main，回到 main',
          '再执行 git log --oneline，对照 main 标签位置',
          'main 最新提交不应包含 feature 上的改动',
        ],
        graphFocus: 'latest',
        practice: {
          label: '切回 main，并用 log 观察分叉',
          command: 'git switch main',
          commands: ['git switch main', 'git log --oneline'],
        },
      },
    ],
    hints: ['switch -c feature → commit → switch main → log。'],
    suggestedCommands: [
      'git switch -c feature',
      'git commit -m "feat: 在 feature 上的改动"',
      'git switch main',
      'git log --oneline',
    ],
    winExplanation: {
      title: '通关：只有当前分支会前进',
      summary: 'commit 推进的是 HEAD 所指分支。',
      detail: '合回 main：switch main 后 merge。',
      related: ['git switch main', 'git merge feature'],
    },
    check: ({ before, after, log }) => checkLevel4(before, after, log),
  },
  {
    id: 7,
    stageId: 's2',
    title: 'Fast-forward 合并',
    story:
      '分叉 = 两条分支各自往前提交，图上长出两条线。无分叉时（如 main 没有新提交、只有 feature 往前）merge 会直接把 main 指针推到 feature 那里（快进），不会新建圆点。',
    intro: {
      summary:
        '什么情况会有分叉？只要「分出去之后」两边又各自 commit，就会分叉。',
      detail:
        '例如从 main 拉出 feature 后：只在 feature 上提交，main 不动 → 还不算两条线都往前，merge 可快进；若 main 也提交了，或两个人在两个分支上各写各的 → 图上出现两条腿，这才叫分叉，合并时往往要新建双父 merge 提交。本关先练「无分叉」的快进合并。',
    },
    objectiveLabels: ['在 main 上完成合并', 'main 已快进到 feature 的最新提交', '没有产生双父 merge 提交'],
    startWorld: startL5,
    concepts: [
      {
        id: 'to-main',
        term: '1 · HEAD 指向 main',
        teaser: '合并发生在 main 上。',
        body: 'merge 推进当前分支。',
        tips: ['先切回 main'],
        graphFocus: 'head',
        practice: { label: '把 HEAD 切回 main', command: 'git switch main' },
      },
      {
        id: 'merge-ff',
        term: '2 · merge feature',
        teaser: 'main 没有独有提交，会快进。',
        body: '不产生新圆点。',
        tips: ['输出 Fast-forward'],
        graphFocus: 'branch',
        practice: { label: '合并 feature', command: 'git merge feature' },
      },
      {
        id: 'no-merge-commit',
        term: '3 · 没有新圆点',
        teaser: '历史仍是直线。',
        body: '快进合并不新增 merge commit。',
        tips: ['对照提交数量'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
    ],
    hints: ['switch main，merge，log。'],
    suggestedCommands: ['git switch main', 'git merge feature', 'git log --oneline'],
    winExplanation: {
      title: '通关：Fast-forward',
      summary: '无分叉时 merge 只前移指针。',
      detail: '下一关练双父 merge。',
      related: ['git log --oneline'],
    },
    check: ({ before, after, log }) => checkLevel5(before, after, log),
  },
  {
    id: 8,
    stageId: 's2',
    title: '生成合并提交',
    story: '学习生成 merge commit：分叉合并后出现双父节点。',
    objectiveLabels: ['HEAD 在 main 上', 'main 最新提交是双父 merge 提交', '该提交能追溯到 feature'],
    startWorld: startL6,
    concepts: [
      {
        id: 'on-main',
        term: '1 · HEAD 在 main',
        teaser: '确认在 main 上。',
        body: 'merge 挂在当前分支。',
        tips: ['若在 feature 上先切回'],
        graphFocus: 'head',
        practice: { label: '确认 HEAD 在 main', command: 'git status' },
      },
      {
        id: 'do-merge',
        term: '2 · 执行 merge',
        teaser: '生成双父圆点。',
        body: '双方都有独有提交时出现 merge commit。',
        tips: ['两条父边'],
        graphFocus: 'commit',
        practice: { label: '合并 feature', command: 'git merge feature' },
      },
      {
        id: 'trace-feature',
        term: '3 · 能追溯到 feature',
        teaser: 'main 能追溯到 feature。',
        body: 'merge commit 记录两边历史。',
        tips: ['log 对照'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
    ],
    hints: ['status，merge，log。'],
    suggestedCommands: ['git switch main', 'git merge feature', 'git log --oneline'],
    winExplanation: {
      title: '通关：双父合并节点',
      summary: 'merge commit 同时记录两边历史。',
      detail: '本沙箱工作区干净时直接生成节点。',
      related: ['git branch -d feature'],
    },
    check: ({ before, after, log }) => checkLevel6(before, after, log),
  },
  {
    id: 9,
    stageId: 's3',
    title: '用 reset 回退',
    story: '学习 git reset：把当前分支指针拨回更早的提交。',
    objectiveLabels: ['已查看当前提交历史', 'main 最新提交已回退到上一个提交', 'HEAD 仍在 main 上'],
    startWorld: startL7,
    concepts: [
      {
        id: 'see-history',
        term: '1 · 先看历史',
        teaser: '回退前先看清最新提交。',
        body: 'reset 会改写分支指针。',
        tips: ['log 只读'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
      {
        id: 'do-reset',
        term: '2 · 回退一步',
        teaser: '把 main 拨回父提交。',
        body: 'HEAD~1 表示父提交。',
        tips: ['指针回退'],
        graphFocus: 'latest',
        practice: { label: '回退 HEAD~1', command: 'git reset --hard HEAD~1' },
      },
      {
        id: 'still-on-main',
        term: '3 · 仍在 main',
        teaser: 'HEAD 应仍在 main。',
        body: 'reset 不切换分支。',
        tips: ['status 确认'],
        graphFocus: 'head',
        practice: { label: '确认仍在 main', command: 'git status' },
      },
    ],
    hints: ['log，reset，status。'],
    suggestedCommands: ['git log --oneline', 'git reset --hard HEAD~1', 'git status'],
    winExplanation: {
      title: '通关：reset 会改历史指针',
      summary: 'reset 把分支指针拨回更早提交。',
      detail: '分享过的提交一般用 revert。',
      related: ['git revert HEAD'],
    },
    check: ({ before, after, log }) => checkLevel7(before, after, log),
  },
  {
    id: 10,
    stageId: 's3',
    title: '协作：push 与 pull',
    story: '学习 push / pull：本地提交如何发布到远程并被他人同步。',
    objectiveLabels: ['Alice 已创建一笔提交', '远程 origin/main 已更新', 'Bob 已 pull 并与远程一致'],
    startWorld: () => createDemoWorld(),
    allowMultiUser: true,
    concepts: [
      {
        id: 'alice-commit-push',
        term: '1 · Alice 提交',
        teaser: '以 Alice 创建一笔提交。',
        body: '本地 commit 只写在自己的仓库。',
        tips: ['顶栏 Alice'],
        graphFocus: 'commit',
        practice: { label: 'Alice 提交', command: 'git commit -m "alice: 共享改动"' },
      },
      {
        id: 'alice-push',
        term: '2 · push 到 origin',
        teaser: '发布到远程。',
        body: '别人要 fetch/pull 才能看到。',
        tips: ['远程 main 前进'],
        graphFocus: 'remote',
        practice: { label: '发布到远程', command: 'git push origin main' },
      },
      {
        id: 'bob-pull',
        term: '3 · Bob 同步',
        teaser: '切到 Bob 后 pull。',
        body: 'pull 把远程合入本地。',
        tips: ['顶栏 Bob'],
        graphFocus: 'remote',
        practice: { label: 'Bob 拉取更新', command: 'git pull' },
      },
    ],
    hints: ['Alice commit，Alice push，Bob pull。'],
    suggestedCommands: ['git commit -m "alice: 共享改动"', 'git push origin main', 'user bob', 'git pull'],
    winExplanation: {
      title: '通关：协作闭环',
      summary: 'push 发布；对方 pull 才同步。',
      detail: '禁止对共享分支 force push。',
      related: ['git fetch', 'user alice'],
    },
    check: ({ before, after, log }) => checkLevel8(before, after, log),
  },
  {
    id: 11,
    stageId: 's4',
    title: '简单 reset：抹掉一笔提交',
    story: '先用 reset 把错误提交从历史上「抹掉」，下一关再用 revert 对比。',
    intro: {
      summary: 'reset 会把分支指针拨回去，历史看起来像那笔从未发生。',
      detail: '下一关的 revert 则是追加一笔抵消提交，旧历史仍在。先通过本关体验「改写历史」的 reset。',
    },
    objectiveLabels: ['用 log 看清要丢掉的提交', '用 reset 抹掉它', '用 log 确认历史里已没有它'],
    startWorld: () => mustRun(createDemoWorld(), ['git commit -m "oops: 这笔要丢掉"']),
    concepts: [
      {
        id: 'see-oops',
        term: '1 · 先看历史',
        teaser: '看清要丢掉的那一笔。',
        body: 'reset 改写分支指针，动手前用 log 确认目标。',
        tips: ['新提交在上', '记住要丢的说明文字'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
      {
        id: 'reset-drop',
        term: '2 · reset 抹掉',
        teaser: '把 main 拨回，错误提交不再被引用。',
        body: 'reset --hard HEAD~1 会移动指针并清空两区标记，历史里将不再出现那一笔。',
        tips: ['指针回退', '图上少一个圆点', '与下一关 revert 对比'],
        graphFocus: 'latest',
        practice: { label: 'reset 抹掉最新提交', command: 'git reset --hard HEAD~1' },
      },
      {
        id: 'gone-forever',
        term: '3 · 历史里已没有它',
        teaser: '再 log：那一笔不见了。',
        body: '这就是「改写历史」。已推送的提交一般不要用 reset 抹掉，见下一关 revert。',
        tips: ['log 对照', '历史被抹掉', '下一关：revert 会保留原提交'],
        graphFocus: 'latest',
        practice: { label: '再查看历史', command: 'git log --oneline' },
      },
    ],
    hints: ['log → reset --hard HEAD~1 → log。', '记住：历史被抹掉；下一关 revert 则不会。'],
    suggestedCommands: ['git log --oneline', 'git reset --hard HEAD~1', 'git log --oneline'],
    winExplanation: {
      title: '通关：reset 抹掉历史',
      summary: 'reset 拨回指针后，那一笔提交从分支历史上消失。',
      detail: '已分享的历史慎用 reset；对比下一关 revert：追加抵消、原提交仍在。',
      related: ['git revert HEAD', 'git log --oneline'],
    },
    check: ({ before, after, log }) => checkLevelResetSimple(before, after, log),
  },
  {
    id: 12,
    stageId: 's4',
    title: 'revert 撤销提交',
    story: '学习 revert：不改写历史，而是追加一笔抵消提交。',
    objectiveLabels: ['已查看当前提交历史', '已 revert 当前提交', '原提交仍在历史中可追溯'],
    startWorld: () => mustRun(createDemoWorld(), ['git commit -m "bad: 需要撤销这笔"']),
    concepts: [
      {
        id: 'see-bad',
        term: '1 · 先看历史',
        teaser: '看清要撤销的那一笔。',
        body: 'revert 会新增提交来抵消内容。',
        tips: ['不要用 reset 抹掉'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
      {
        id: 'do-revert',
        term: '2 · 执行 revert',
        teaser: '生成 Revert 开头的新提交。',
        body: '原提交仍在。',
        tips: ['图上多一圆点'],
        graphFocus: 'commit',
        practice: { label: '撤销当前提交', command: 'git revert HEAD' },
      },
      {
        id: 'still-there',
        term: '3 · 原提交仍可追溯',
        teaser: 'log 确认历史仍向前。',
        body: '这是与 reset 的关键差别。',
        tips: ['适合已推送的提交'],
        graphFocus: 'latest',
        practice: { label: '再看历史', command: 'git log --oneline' },
      },
    ],
    hints: ['log，revert，log。'],
    suggestedCommands: ['git log --oneline', 'git revert HEAD', 'git log --oneline'],
    winExplanation: {
      title: '通关：revert 不改写历史',
      summary: 'revert 追加抵消提交；reset 拨回指针。',
      detail: '公共分支优先 revert。',
      related: ['git reset --soft HEAD~1'],
    },
    check: ({ before, after, log }) => checkLevel10(before, after, log),
  },
  {
    id: 13,
    stageId: 's4',
    title: 'rebase 线性化',
    story: '学习 rebase：把 feature 的独有提交接到 main 之上。',
    objectiveLabels: ['HEAD 在 feature 上', '已把 feature rebase 到 main 之上', '用 log 确认更线性'],
    startWorld: startL6,
    concepts: [
      {
        id: 'on-feat',
        term: '1 · 在 feature 上',
        teaser: 'rebase 的是当前分支。',
        body: '独有提交会被重放到目标分支的最新提交之上。',
        tips: ['HEAD 应在 feature'],
        graphFocus: 'head',
        practice: { label: 'HEAD 指向 feature', command: 'git switch feature' },
      },
      {
        id: 'do-rebase',
        term: '2 · rebase main',
        teaser: '把 feature 接到 main 之上。',
        body: '历史更线性。',
        tips: ['共享分支慎用'],
        graphFocus: 'latest',
        practice: { label: '变基到 main', command: 'git rebase main' },
      },
      {
        id: 'see-linear',
        term: '3 · 观察线性历史',
        teaser: '没有双父节点。',
        body: '与 merge 对比。',
        tips: ['单父'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
    ],
    hints: ['switch feature，rebase main，log。'],
    suggestedCommands: ['git switch feature', 'git rebase main', 'git log --oneline'],
    winExplanation: {
      title: '通关：rebase',
      summary: '把当前分支独有提交重放到目标分支的最新提交之上。',
      detail: '不要 rebase 已共享的公共历史。',
      related: ['git merge main'],
    },
    check: ({ before, after, log }) => checkLevel11(before, after, log),
  },
  {
    id: 14,
    stageId: 's4',
    title: 'git cherry-pick（只摘 bugfix）',
    story: '从 feature 的多笔提交中，只把 bugfix 摘到 main（真实场景常见）。',
    objectiveLabels: [
      '用 log 找到 feature 上的 bugfix 提交',
      '只把该 bugfix cherry-pick 到 main',
      'main 多一条 fix 提交，且不含 feat 提交',
    ],
    startWorld: startCherryPick,
    concepts: [
      {
        id: 'find-cp',
        term: '1 · 找到目标提交',
        teaser: '用 log 在 feature 上找到 fix 的短 hash。',
        body: '源分支指针不动。',
        tips: ['记下短 hash'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
      {
        id: 'do-cp',
        term: '2 · 执行 cherry-pick',
        teaser: 'feature 上有多笔提交，main 只需要其中的 bugfix。',
        body: '只复制一个提交。',
        tips: [
          '在 log 里找「fix: 紧急修复登录」，记下短 hash（f55adc7）',
          '在 main 上执行 git cherry-pick f55adc7',
          '不要摘「feat: 功能开发 1/2」',
        ],
        graphFocus: 'commit',
        practice: {
          label: '只摘「fix: 紧急修复登录」到 main',
          command: 'git cherry-pick f55adc7',
        },
      },
      {
        id: 'see-cp',
        term: '3 · 确认多了一条',
        teaser: 'log 确认历史变长。',
        body: '说明与原提交相同。',
        tips: ['feature 未变'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
    ],
    hints: [
      'log 找到「fix: 紧急修复登录」的短 hash。',
      '在 main 上 cherry-pick 该短 hash（只摘 fix）。',
      '再 log：main 只多 fix，不应多出 feat。',
    ],
    suggestedCommands: ['git log --oneline', 'git cherry-pick <短hash>', 'git log --oneline'],
    winExplanation: {
      title: '通关：cherry-pick',
      summary: '只把一个提交复制到当前分支。',
      detail: '沙箱始终成功。',
      related: ['git rebase main'],
    },
    check: ({ before, after, log }) => checkLevelCherryPick(before, after, log),
  },
  {
    id: 15,
    stageId: 's5',
    title: 'fetch 与 pull',
    story: '区分 fetch 与 pull。',
    objectiveLabels: ['Alice 已 commit 并 push', 'Bob 已 fetch', 'Bob 已 pull 并与远程一致'],
    startWorld: () => mustRun(createDemoWorld(), ['git commit -m "alice: 待发布"']),
    allowMultiUser: true,
    concepts: [
      {
        id: 'alice-publish',
        term: '1 · Alice 发布',
        teaser: 'Alice 先 push。',
        body: 'Bob 不会自动看到。',
        tips: ['顶栏 Alice'],
        graphFocus: 'remote',
        practice: { label: 'Alice 提交并 push', command: 'git push origin main' },
      },
      {
        id: 'bob-fetch',
        term: '2 · Bob fetch',
        teaser: '只更新远程引用。',
        body: '本地 main 可不变。',
        tips: ['先 fetch 再观察'],
        graphFocus: 'remote',
        practice: { label: 'Bob fetch', command: 'git fetch' },
      },
      {
        id: 'bob-pull-sync',
        term: '3 · Bob pull',
        teaser: '合入本地。',
        body: 'pull 等于 fetch 加合并。',
        tips: ['与 origin 一致'],
        graphFocus: 'remote',
        practice: { label: 'Bob pull', command: 'git pull' },
      },
    ],
    hints: ['Alice push，Bob fetch，Bob pull。'],
    suggestedCommands: ['git push origin main', 'user bob', 'git fetch', 'git pull'],
    winExplanation: {
      title: '通关：fetch 不等于 pull',
      summary: 'fetch 更新引用；pull 才合并。',
      detail: '先看远程再合并时用 fetch。',
      related: ['git remote -v'],
    },
    check: ({ before, after, log }) => checkLevel12(before, after, log),
  },
  {
    id: 16,
    stageId: 's5',
    title: 'push 被拒绝',
    story: '远程有你本地没有的提交时，push 无法快进完成，会被拒；先 pull 再 push。',
    objectiveLabels: ['push 被拒绝', '已 pull 同步', '再次 push 成功'],
    startWorld: () => {
      let w = mustRun(createDemoWorld(), ['git commit -m "alice: 本地未推"']);
      w = applyWorldCommand(w, 'user bob').world;
      w = mustRun(w, ['git commit -m "bob: 已推远程"', 'git push origin main']);
      w = applyWorldCommand(w, 'user alice').world;
      return w;
    },
    allowMultiUser: true,
    concepts: [
      {
        id: 'try-push',
        term: '1 · 尝试 push',
        teaser: '分叉后 push 会被拒。',
        body: 'push 只能快进，不能覆盖他人提交。',
        tips: ['不要 force'],
        graphFocus: 'remote',
        practice: { label: 'Alice push', command: 'git push origin main' },
      },
      {
        id: 'do-pull',
        term: '2 · pull 同步',
        teaser: '先合并远程。',
        body: '本地包含双方历史。',
        tips: ['仍在 Alice'],
        graphFocus: 'remote',
        practice: { label: 'Alice pull', command: 'git pull' },
      },
      {
        id: 'push-again',
        term: '3 · 再次 push',
        teaser: '同步后应成功。',
        body: '协作闭环完成。',
        tips: ['再次 push'],
        graphFocus: 'remote',
        practice: { label: '再次 push', command: 'git push origin main' },
      },
    ],
    hints: ['push 失败，pull，再 push。'],
    suggestedCommands: ['git push origin main', 'git pull', 'git push origin main'],
    winExplanation: {
      title: '通关：push 保护',
      summary: '远程有你本地没有的提交时，push 会被拒。',
      detail: '快进 = 远程分支指针沿同一条历史前移到你的最新提交。远程有你没有的提交时无法快进，直接 push 会覆盖他人提交，所以被拒。不要 force push。',
      related: ['git pull'],
    },
    check: ({ before, after, log }) => checkLevel13(before, after, log),
  },
  {
    id: 17,
    stageId: 's5',
    title: 'pull 产生合并',
    story: '双方各自有新提交（历史分叉）时，pull 默认合并，会生成双父提交。',
    objectiveLabels: ['Bob 本地已有提交', 'pull 后是双父 merge', '能追溯到远程提交'],
    startWorld: () => {
      let w = mustRun(createDemoWorld(), [
        'git commit -m "alice: 已推到远程"',
        'git push origin main',
      ]);
      w = applyWorldCommand(w, 'user bob').world;
      return w;
    },
    allowMultiUser: true,
    concepts: [
      {
        id: 'bob-commit',
        term: '1 · Bob 本地提交',
        teaser: '制造分叉。',
        body: '远程已有 Alice 的提交。',
        tips: ['顶栏 Bob'],
        graphFocus: 'commit',
        practice: { label: 'Bob 提交', command: 'git commit -m "bob: 仅在本地"' },
      },
      {
        id: 'bob-pull-merge',
        term: '2 · pull 合并',
        teaser: '默认生成双父节点。',
        body: '与快进合并不同，会新建 merge 提交。',
        tips: ['两条父边'],
        graphFocus: 'commit',
        practice: { label: 'Bob pull', command: 'git pull' },
      },
      {
        id: 'see-both',
        term: '3 · 含双方历史',
        teaser: '能追溯到远程提交。',
        body: 'merge 记录两边。',
        tips: ['log 对照'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
    ],
    hints: ['Bob commit，pull，log。'],
    suggestedCommands: ['git commit -m "bob: 仅在本地"', 'git pull', 'git log --oneline'],
    winExplanation: {
      title: '通关：pull 合并',
      summary: '历史分叉时，pull 默认合并并生成双父提交。',
      detail: '单方前进时 pull 可快进，不新建节点；双方都有新提交才合并。也可 rebase 到 origin 之上。',
      related: ['git rebase origin/main'],
    },
    check: ({ before, after, log }) => checkLevel14(before, after, log),
  },
  {
    id: 18,
    stageId: 's5',
    title: '删除分支',
    story: '用 -d 删已合并分支；未合并时 -d 拒绝，需 -D 强制。',
    objectiveLabels: ['删除已合并的 feature', '未合并分支 -d 被拒绝', '用 -D 删除 hotfix'],
    startWorld: () =>
      mustRun(createDemoWorld(), [
        'git switch -c feature',
        'git commit -m "feat: 已完成"',
        'git switch main',
        'git merge feature',
        'git switch -c hotfix',
        'git commit -m "wip: 未合并的工作"',
        'git switch main',
      ]),
    concepts: [
      {
        id: 'del-merged',
        term: '1 · 删除已合并分支',
        teaser: 'feature 已合并进 main。',
        body: '-d 只删已合并分支。',
        tips: ['分支名消失'],
        graphFocus: 'branch',
        practice: { label: '删除 feature', command: 'git branch -d feature' },
      },
      {
        id: 'del-unmerged-fail',
        term: '2 · -d 拒绝未合并',
        teaser: 'hotfix 有未合并提交。',
        body: '-d 拒绝删除，避免丢提交。',
        tips: ['阅读拒绝原因'],
        graphFocus: 'branch',
        practice: { label: '尝试删除 hotfix', command: 'git branch -d hotfix' },
      },
      {
        id: 'force-del',
        term: '3 · -D 强制删除',
        teaser: '确认不再需要这些提交。',
        body: '-D 跳过合并检查，强制删除。',
        tips: ['hotfix 消失'],
        graphFocus: 'branch',
        practice: { label: '强制删除 hotfix', command: 'git branch -D hotfix' },
      },
    ],
    hints: ['-d feature，-d hotfix 会被拒，再 -D hotfix。'],
    suggestedCommands: ['git branch -d feature', 'git branch -d hotfix', 'git branch -D hotfix'],
    winExplanation: {
      title: '通关：删分支',
      summary: '-d 只删已合并；未合并需 -D 强制。',
      detail: '删的是分支名（指针）；提交对象仍在，不可达后才会被清理。',
      related: ['git log --oneline'],
    },
    check: ({ before, after, log }) => checkLevel15(before, after, log),
  },
  {
    id: 19,
    stageId: 's5',
    title: 'rebase 到 origin',
    story: '协作中把本地提交 rebase 到 origin/main。',
    objectiveLabels: ['已 fetch', '已 rebase 到 origin/main', 'log 显示线性'],
    startWorld: () => {
      let w = mustRun(createDemoWorld(), ['git commit -m "alice: 远程新提交"']);
      w = mustRun(w, ['git push origin main']);
      w = applyWorldCommand(w, 'user bob').world;
      w = mustRun(w, ['git commit -m "bob: 本地工作"']);
      return w;
    },
    allowMultiUser: true,
    concepts: [
      {
        id: 'fetch-origin',
        term: '1 · fetch 远程',
        teaser: '先更新 origin/main。',
        body: 'Bob 本地也有提交。',
        tips: ['顶栏 Bob'],
        graphFocus: 'remote',
        practice: { label: 'Bob fetch', command: 'git fetch' },
      },
      {
        id: 'rebase-origin',
        term: '2 · rebase origin/main',
        teaser: '本地提交接到远程之上。',
        body: '保持线性。',
        tips: ['勿 rebase 公共历史'],
        graphFocus: 'latest',
        practice: { label: '变基到远程', command: 'git rebase origin/main' },
      },
      {
        id: 'see-on-top',
        term: '3 · 观察线性结果',
        teaser: '本地在远程之上。',
        body: '可再 push。',
        tips: ['单父'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
    ],
    hints: ['fetch，rebase origin/main，log。'],
    suggestedCommands: ['git fetch', 'git rebase origin/main', 'git log --oneline'],
    winExplanation: {
      title: '通关：rebase origin',
      summary: '先 fetch 再 rebase origin/分支。',
      detail: '仍避免 force push。',
      related: ['git push origin main'],
    },
    check: ({ before, after, log }) => checkLevel16(before, after, log),
  },
  {
    id: 20,
    stageId: 's6',
    title: '工作区与暂存区',
    story: '认识工作区与暂存区，用 status 看清两区。',
    objectiveLabels: ['执行 status 看清两区', '执行 git add 放入暂存区', '再用 status 确认暂存区有内容'],
    startWorld: startDirty,
    concepts: [
      {
        id: 'see-zones',
        term: '1 · 看清两区',
        teaser: 'status 分区显示工作区与暂存区。',
        body: '工作区是正在改的内容；暂存区是下次 commit 要记进去的内容。',
        tips: ['沙箱两态模拟'],
        graphFocus: 'latest',
        practice: { label: '查看两区状态', command: 'git status' },
      },
      {
        id: 'do-add',
        term: '2 · git add',
        teaser: '把改动放进暂存区。',
        body: '沙箱用 git add . 表示全部暂存。',
        tips: ['工作区变干净'],
        graphFocus: 'commit',
        practice: { label: '暂存全部改动', command: 'git add .' },
      },
      {
        id: 're-status',
        term: '3 · 再次 status',
        teaser: '确认暂存区有内容。',
        body: '下一步 commit。',
        tips: ['对照两区文案'],
        graphFocus: 'latest',
        practice: { label: '再次查看状态', command: 'git status' },
      },
    ],
    hints: ['status，add，status。'],
    suggestedCommands: ['git status', 'git add .', 'git status'],
    winExplanation: {
      title: '通关：两区模型',
      summary: '工作区到 add 到暂存区到 commit 到历史。',
      detail: '沙箱两态即可建立概念。',
      related: ['git diff', 'git commit -m "..."'],
    },
    check: ({ before, after, log }) => checkLevelWorkspace(before, after, log),
  },
  {
    id: 21,
    stageId: 's6',
    title: 'git add 与 commit',
    story: '完成 add 到 status 到 commit 闭环。',
    objectiveLabels: ['执行 git add', '用 status 看到暂存区有内容', 'commit 后两区变干净并新增提交'],
    startWorld: startDirty,
    concepts: [
      {
        id: 'add-only',
        term: '1 · 先 add',
        teaser: '把工作区改动放进暂存区。',
        body: '本阶段 commit 前应先 add。',
        tips: ['旧关仍可直接 commit'],
        graphFocus: 'commit',
        practice: { label: '暂存改动', command: 'git add .' },
      },
      {
        id: 'check-staged',
        term: '2 · status 确认',
        teaser: '确认暂存区有内容。',
        body: 'commit 只记录暂存内容。',
        tips: ['暂存区有已暂存改动'],
        graphFocus: 'latest',
        practice: { label: '查看状态', command: 'git status' },
      },
      {
        id: 'do-commit',
        term: '3 · 提交',
        teaser: '把暂存内容记入历史。',
        body: 'commit 后图上多一圆点。',
        tips: ['新圆点闪烁'],
        graphFocus: 'commit',
        practice: { label: '提交暂存内容', command: 'git commit -m "docs: 更新说明"' },
      },
    ],
    hints: ['add，status，commit。'],
    suggestedCommands: ['git add .', 'git status', 'git commit -m "docs: 更新说明"'],
    winExplanation: {
      title: '通关：add 到 commit',
      summary: '标准流程：先暂存再提交。',
      detail: '旧关卡可直接 commit，属教学简化。',
      related: ['git diff --staged'],
    },
    check: ({ before, after, log }) => checkLevelAdd(before, after, log),
  },
  {
    id: 22,
    stageId: 's6',
    title: 'git diff',
    story: '用 diff 查看工作区与暂存区改动。',
    objectiveLabels: ['执行 git diff 看工作区改动', '执行 git add', '执行 git diff --staged 看暂存区改动'],
    startWorld: startDirty,
    concepts: [
      {
        id: 'diff-work',
        term: '1 · diff 工作区',
        teaser: '看未 add 的改动。',
        body: '沙箱只显示有/无两态。',
        tips: ['不列文件级 diff'],
        graphFocus: 'latest',
        practice: { label: '查看工作区差异', command: 'git diff' },
      },
      {
        id: 'then-add',
        term: '2 · add 进暂存',
        teaser: '把改动放进暂存区。',
        body: '内容进入暂存区。',
        tips: ['git add .'],
        graphFocus: 'commit',
        practice: { label: '暂存改动', command: 'git add .' },
      },
      {
        id: 'diff-staged',
        term: '3 · diff --staged',
        teaser: '看已暂存待提交差异。',
        body: '与 git diff 对照。',
        tips: ['沙箱两态'],
        graphFocus: 'latest',
        practice: { label: '查看暂存区差异', command: 'git diff --staged' },
      },
    ],
    hints: ['diff，add，diff --staged。'],
    suggestedCommands: ['git diff', 'git add .', 'git diff --staged'],
    winExplanation: {
      title: '通关：diff',
      summary: 'diff 看未暂存；diff --staged 看已暂存。',
      detail: '沙箱不列文件名。',
      related: ['git status', 'git restore .'],
    },
    check: ({ before, after, log }) => checkLevelDiff(before, after, log),
  },
  {
    id: 23,
    stageId: 's6',
    title: 'git restore',
    story: '用 restore 丢弃工作区改动或从暂存区撤回。',
    objectiveLabels: ['丢弃工作区改动', 'status 确认工作区干净', '理解 restore --staged'],
    startWorld: startDirty,
    concepts: [
      {
        id: 'drop-work',
        term: '1 · 丢弃工作区',
        teaser: '不想要的未 add 改动可丢掉。',
        body: '危险且不可恢复。',
        tips: ['先想清楚'],
        graphFocus: 'latest',
        practice: { label: '丢弃工作区改动', command: 'git restore .' },
      },
      {
        id: 'check-clean',
        term: '2 · status 确认',
        teaser: '工作区应干净。',
        body: '对照两区。',
        tips: ['status'],
        graphFocus: 'latest',
        practice: { label: '查看状态', command: 'git status' },
      },
      {
        id: 'unstage',
        term: '3 · restore --staged',
        teaser: '把暂存改动撤回工作区。',
        body: '不丢内容。',
        tips: ['可先 add 再试'],
        graphFocus: 'commit',
        practice: { label: '从暂存区撤回', command: 'git restore --staged' },
      },
    ],
    hints: ['restore，status，restore --staged。'],
    suggestedCommands: ['git restore .', 'git status', 'git add .', 'git restore --staged'],
    winExplanation: {
      title: '通关：restore',
      summary: 'restore 点 丢工作区；restore --staged 只撤暂存。',
      detail: '丢弃前可先 stash。',
      related: ['git stash'],
    },
    check: ({ before, after, log }) => checkLevelRestore(before, after, log),
  },
  {
    id: 24,
    stageId: 's6',
    title: 'git stash / pop',
    story: '把未完成的改动收起来，稍后再恢复。',
    objectiveLabels: ['执行 git stash 保存现场', '工作区变干净', '执行 git stash pop 恢复现场'],
    startWorld: startDirty,
    concepts: [
      {
        id: 'do-stash',
        term: '1 · stash 现场',
        teaser: '切分支前先收起来。',
        body: '工作区变干净。',
        tips: ['stash 不进历史'],
        graphFocus: 'latest',
        practice: { label: '保存现场', command: 'git stash' },
      },
      {
        id: 'clean-check',
        term: '2 · status 确认',
        teaser: '工作区应干净。',
        body: '可安全切换。',
        tips: ['对照两区'],
        graphFocus: 'latest',
        practice: { label: '查看状态', command: 'git status' },
      },
      {
        id: 'do-pop',
        term: '3 · stash pop',
        teaser: '恢复现场。',
        body: '改动回到工作区。',
        tips: ['栈顶弹出'],
        graphFocus: 'latest',
        practice: { label: '恢复现场', command: 'git stash pop' },
      },
    ],
    hints: ['stash，status，stash pop。'],
    suggestedCommands: ['git stash', 'git status', 'git stash pop'],
    winExplanation: {
      title: '通关：stash',
      summary: 'stash 暂存现场；pop 恢复。',
      detail: '可用 stash list 查看。',
      related: ['git stash list'],
    },
    check: ({ before, after, log }) => checkLevelStash(before, after, log),
  },
  {
    id: 25,
    stageId: 's6',
    title: 'soft / mixed / hard 对比',
    story: '学习 reset 三种模式对暂存区/工作区的差别。',
    objectiveLabels: [
      '已查看当前提交历史',
      '已用 soft reset 回退一步',
      '已用 mixed reset 对比暂存区',
      '已用 hard reset 再回退并清空两区',
    ],
    startWorld: startSoftHard,
    concepts: [
      {
        id: 'see-two-oops',
        term: '1 · 先看历史',
        teaser: '看清两笔错误提交。',
        body: '回退前用 log 记下位置。',
        tips: ['新提交在上'],
        graphFocus: 'latest',
        practice: { label: '查看历史', command: 'git log --oneline' },
      },
      {
        id: 'soft-reset',
        term: '2 · soft 回退',
        teaser: '只拨指针，保留两区标记。',
        body: 'status 仍显示有改动。',
        tips: ['可接着 commit'],
        graphFocus: 'latest',
        practice: { label: 'soft 回退', command: 'git reset --soft HEAD~1' },
      },
      {
        id: 'mixed-reset',
        term: '3 · mixed 对比',
        teaser: '默认模式：暂存区清空，改动回工作区。',
        body: '介于 soft 与 hard 之间。用 status 对比文案。',
        tips: ['暂存区变空'],
        graphFocus: 'latest',
        practice: { label: 'mixed 回退', command: 'git reset --mixed HEAD~1' },
      },
      {
        id: 'hard-reset',
        term: '4 · hard 再回退',
        teaser: '再拨一步并清空两区。',
        body: 'hard 同时清工作区标记。',
        tips: ['对比三种模式'],
        graphFocus: 'latest',
        practice: { label: 'hard 回退', command: 'git reset --hard HEAD~1' },
      },
    ],
    hints: ['log，soft，mixed，hard。'],
    suggestedCommands: [
      'git log --oneline',
      'git reset --soft HEAD~1',
      'git reset --mixed HEAD~1',
      'git reset --hard HEAD~1',
    ],
    winExplanation: {
      title: '通关：soft / mixed / hard',
      summary: '都移动指针；soft 保标记，mixed 清暂存，hard 全清。',
      detail: '已分享历史优先 revert。',
      related: ['git revert HEAD', 'git status'],
    },
    check: ({ before, after, log }) => checkLevel9(before, after, log),
  },
];

export function getLevel(id: number): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function maxLevelId(): number {
  return LEVELS[LEVELS.length - 1]?.id ?? 1;
}
